### ISSUE TITLE
Unit test support

### ISSUE THREAD

**Issue by nheezemans** [tideman/generator-ciberionic#6]
AngularJS Unit test support (Karma, PhantomJS, Protractor etc.). Declare the tests in ./test folder per module

**Comment by tideman** [comment]
Wordt iets anders. Elk component krijg een spec file.
De tests staan dus meteen naast bv de controller file

VB

dashboard.controller.js
dashboard.controller.spec.js

Gulp raapt alle tests bijelkaar
